// core.js の公開エクスポート一覧を固定するリグレッションテスト。
// リファクタ（分割・移動）で意図せず公開APIが増減していないかを検出する。
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as core from '@core';

const EXPECTED_EXPORTS = [
  'Arc',
  'CL_OVERLAP_TOL_MM',
  'CenterLine',
  'CenterLineType',
  'Circle',
  'ColumnBase',
  'DEFAULT_CEILING_BACKING',
  'DEFAULT_EXTERIOR_WALL_BACKING',
  'DEFAULT_FLOOR_BACKING',
  'DEFAULT_INTERIOR_WALL_BACKING',
  'DEFAULT_ROOM_CEILING_HEIGHT',
  'DEFAULT_ROOM_FLOOR_LEVEL',
  'DEFAULT_WALL_MATERIAL',
  'DiagonalLine',
  'DimensionAnchor',
  'DimensionKind',
  'DimensionSide',
  'Discipline',
  'Edge',
  'ExteriorFinishRow',
  'HDimensionLine',
  'HOST_BEAM_MATCH_TOL_MM',
  'HorizontalLine',
  'IndependentFooting',
  'Intersection',
  'LINE_WEIGHT_MM',
  'Opening',
  'OpeningCategory',
  'PenetrationSleeve',
  'PlanGraph',
  'Plane',
  'Point',
  'Project',
  'RcBeam',
  'RcBearingWall',
  'RcColumn',
  'RcSlab',
  'RcWallOpening',
  'Room',
  'RoomFeature',
  'RoomFinish',
  'RoomKind',
  'ShapeKind',
  'ShapeType',
  'Site',
  'SiteLine',
  'SiteLineKind',
  'SitePoint',
  'SiteTriangle',
  'Stair',
  'StairType',
  'SteelBeam',
  'SteelColumn',
  'StructuralBeam',
  'StructuralColumn',
  'StructuralInfo',
  'StructuralMaterialType',
  'StructuralSlab',
  'StructuralWall',
  'VDimensionLine',
  'VerticalLine',
  'Wall',
  'WallBackingMaterial',
  'WoodBeam',
  'WoodColumn',
  'centerLineKind',
  'columnSlotKey',
  'edgeKey',
  'findHostPrimaryBeam',
  'spanKey',
  'totalStepsFromSections',
].sort();

test('core.js: 公開エクスポート一覧が既知のセットと一致する（リファクタでの意図しない増減を検出）', () => {
  assert.deepEqual(Object.keys(core).sort(), EXPECTED_EXPORTS);
});
